#pragma once

#include <string>
#include <vector>
#include <sstream>
#include "Parser.h" // Needed for the Instruction struct and TokenType enum

class Generator {
public:
    // Constructor takes the AST generated by the Parser
    explicit Generator(const std::vector<Instruction>& program);

    // Kicks off the translation and returns the full C source code as a string
    std::string generate();

private:
    // The abstract syntax tree we are going to translate
    std::vector<Instruction> m_program;

    // Recursive helper function to handle nested loops cleanly
    void generateInstructions(const std::vector<Instruction>& instructions, std::stringstream& out, int indentLevel);

    // Helper to generate spaces so your output C code is nicely formatted!
    std::string getIndent(int level) const;
};
